-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 14:45:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ArtGalleryManagementDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS ArtGalleryManagementDB;
CREATE DATABASE IF NOT EXISTS ArtGalleryManagementDB;
USE ArtGalleryManagementDB;
-- -----------------------------------------------------
-- Table `general_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `general_user` ;

CREATE TABLE IF NOT EXISTS `general_user` (
  `general_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`general_user_id`),
  UNIQUE INDEX `general_user_id_UNIQUE` (`general_user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `unregistered_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unregistered_user` ;

CREATE TABLE IF NOT EXISTS `unregistered_user` (
  `unregistered_user_id` INT NOT NULL,
  `general_user_general_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`unregistered_user_id`, `general_user_general_user_id`),
  INDEX `fk_unregistered_user_general_user1_idx` (`general_user_general_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_unregistered_user_general_user1`
    FOREIGN KEY (`general_user_general_user_id`)
    REFERENCES `general_user` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `registered_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registered_user` ;

CREATE TABLE IF NOT EXISTS `registered_user` (
  `registered_user_id` INT NOT NULL,
  `username` VARCHAR(24) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(255) NOT NULL,
  `general_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`registered_user_id`, `general_user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_registered_user_general_user1_idx` (`general_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_registered_user_general_user1`
    FOREIGN KEY (`general_user_id`)
    REFERENCES `general_user` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `role_id` INT NOT NULL,
  `role_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE);

-- -----------------------------------------------------
-- Table `assigned`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assigned` ;

CREATE TABLE IF NOT EXISTS `assigned` (
  `id` INT NOT NULL,
  `registered_user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `registered_user_id`, `role_id`),
  INDEX `fk_registered_user_has_has_has1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_registered_user_has_has_registered_user_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_registered_user_has_has_registered_user`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `registered_user` (`registered_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registered_user_has_has_has1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gallery` ;

CREATE TABLE IF NOT EXISTS `gallery` (
  `gallery_id` INT NOT NULL,
  `gallery_name` VARCHAR(255) NOT NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`gallery_id`, `registered_user_id`),
  INDEX `fk_gallery_registered_user1_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_gallery_registered_user1`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `registered_user` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artist` ;

CREATE TABLE IF NOT EXISTS `artist` (
  `artist_id` INT NOT NULL,
  `birthday` VARCHAR(45) NULL,
  `biography` VARCHAR(255) NOT NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`artist_id`, `registered_user_id`),
  INDEX `fk_artist_registered_user1_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_artist_registered_user1`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `registered_user` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `registered_user_id`),
  INDEX `fk_customer_registered_user1_idx` (`registered_user_id` ASC) VISIBLE,
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_registered_user1`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `registered_user` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `artwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artwork` ;

CREATE TABLE IF NOT EXISTS `artwork` (
  `artwork_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `availability` TINYINT NOT NULL,
  `description` VARCHAR(255) NULL,
  `customer_id` INT NULL,
  `gallery_id` INT NULL,
  PRIMARY KEY (`artwork_id`),
  INDEX `fk_artwork_gallery1_idx` (`gallery_id` ASC) VISIBLE,
  INDEX `fk_artwork_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_artwork_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `gallery` (`gallery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `creates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creates` ;

CREATE TABLE IF NOT EXISTS `creates` (
  `artist_artist_id` INT NOT NULL,
  `artwork_category_id` INT NOT NULL,
  PRIMARY KEY (`artist_artist_id`, `artwork_category_id`),
  INDEX `fk_artist_has_artwork_artwork1_idx` (`artwork_category_id` ASC) VISIBLE,
  INDEX `fk_artist_has_artwork_artist1_idx` (`artist_artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_artist_has_artwork_artist1`
    FOREIGN KEY (`artist_artist_id`)
    REFERENCES `artist` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artist_has_artwork_artwork1`
    FOREIGN KEY (`artwork_category_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
-- -----------------------------------------------------
-- Table `painting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `painting` ;

CREATE TABLE IF NOT EXISTS `painting` (
  `painting_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`painting_id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  UNIQUE INDEX `painting_id_UNIQUE` (`painting_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork1`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `architecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `architecture` ;

CREATE TABLE IF NOT EXISTS `architecture` (
  `architecture_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`architecture_id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  UNIQUE INDEX `painting_id_UNIQUE` (`architecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork10`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `sculpture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sculpture` ;

CREATE TABLE IF NOT EXISTS `sculpture` (
  `sculpture_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`sculpture_id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  UNIQUE INDEX `painting_id_UNIQUE` (`sculpture_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork11`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `photograph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photograph` ;

CREATE TABLE IF NOT EXISTS `photograph` (
  `photograph_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`photograph_id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  UNIQUE INDEX `painting_id_UNIQUE` (`photograph_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork12`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `music`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music` ;

CREATE TABLE IF NOT EXISTS `music` (
  `music_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`music_id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  UNIQUE INDEX `painting_id_UNIQUE` (`music_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork13`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `graphic_design`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graphic_design` ;

CREATE TABLE IF NOT EXISTS `graphic_design` (
  `graphic_design_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`graphic_design_id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  UNIQUE INDEX `painting_id_UNIQUE` (`graphic_design_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork130`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `image` ;

CREATE TABLE IF NOT EXISTS `image` (
  `img_id` INT NOT NULL,
  `img_upload` VARCHAR(255) NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`img_id`, `artwork_id`),
  INDEX `fk_image_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  UNIQUE INDEX `img_id_UNIQUE` (`img_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_artwork1`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genre` ;

CREATE TABLE IF NOT EXISTS `genre` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`genre_id`));

-- -----------------------------------------------------
-- Table `artwork_has_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artwork_has_genre` ;

CREATE TABLE IF NOT EXISTS `artwork_has_genre` (
  `genre_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`genre_id`, `artwork_id`),
  INDEX `fk_genre_has_artwork_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  INDEX `fk_genre_has_artwork_genre1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_genre_has_artwork_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `genre` (`genre_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_genre_has_artwork_artwork1`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `artwork` (`artwork_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

CREATE TABLE IF NOT EXISTS `address` (
  `address_id` INT NOT NULL,
  `street_name` VARCHAR(255) NOT NULL,
  `street_num` INT NOT NULL,
  `zip_code` INT NOT NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`address_id`, `customer_id`),
  INDEX `fk_address_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `director` ;

CREATE TABLE IF NOT EXISTS `director` (
  `director_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`director_id`));

-- -----------------------------------------------------
-- Table `director_has_gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `director_has_gallery` ;

CREATE TABLE IF NOT EXISTS `director_has_gallery` (
  `director_id` INT NOT NULL,
  `gallery_id` INT NOT NULL,
  PRIMARY KEY (`director_id`, `gallery_id`),
  INDEX `fk_director_has_gallery_gallery1_idx` (`gallery_id` ASC) VISIBLE,
  INDEX `fk_director_has_gallery_director1_idx` (`director_id` ASC) VISIBLE,
  CONSTRAINT `fk_director_has_gallery_director1`
    FOREIGN KEY (`director_id`)
    REFERENCES `director` (`director_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_director_has_gallery_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `gallery` (`gallery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `artstyle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artstyle` ;

CREATE TABLE IF NOT EXISTS `artstyle` (
  `artstyle_id` INT NOT NULL,
  `style_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`artstyle_id`));

-- -----------------------------------------------------
-- Table `painting_has_artstyle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `painting_has_artstyle` ;

CREATE TABLE IF NOT EXISTS `painting_has_artstyle` (
  `painting_id` INT NOT NULL,
  `artstyle_id` INT NOT NULL,
  PRIMARY KEY (`painting_id`, `artstyle_id`),
  INDEX `fk_painting_has_artstyle_artstyle1_idx` (`artstyle_id` ASC) VISIBLE,
  INDEX `fk_painting_has_artstyle_painting1_idx` (`painting_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_has_artstyle_painting1`
    FOREIGN KEY (`painting_id`)
    REFERENCES `painting` (`painting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_painting_has_artstyle_artstyle1`
    FOREIGN KEY (`artstyle_id`)
    REFERENCES `artstyle` (`artstyle_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material` ;

CREATE TABLE IF NOT EXISTS `material` (
  `material_id` INT NOT NULL,
  `material_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`material_id`));

-- -----------------------------------------------------
-- Table `material_has_sculpture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material_has_sculpture` ;

CREATE TABLE IF NOT EXISTS `material_has_sculpture` (
  `material_id` INT NOT NULL,
  `sculpture_id` INT NOT NULL,
  PRIMARY KEY (`material_id`, `sculpture_id`),
  INDEX `fk_material_has_sculpture_sculpture1_idx` (`sculpture_id` ASC) VISIBLE,
  INDEX `fk_material_has_sculpture_material1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_material_has_sculpture_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `material` (`material_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_material_has_sculpture_sculpture1`
    FOREIGN KEY (`sculpture_id`)
    REFERENCES `sculpture` (`sculpture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_method` ;

CREATE TABLE IF NOT EXISTS `payment_method` (
  `payment_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`payment_id`));

-- -----------------------------------------------------
-- Table `customer_has_payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer_has_payment_method` ;

CREATE TABLE IF NOT EXISTS `customer_has_payment_method` (
  `customer_customer_id` INT NOT NULL,
  `payment_method_category_id` INT NOT NULL,
  INDEX `fk_customer_has_payment_method_payment_method1_idx` (`payment_method_category_id` ASC) VISIBLE,
  INDEX `fk_customer_has_payment_method_customer1_idx` (`customer_customer_id` ASC) VISIBLE,
  PRIMARY KEY (`customer_customer_id`, `payment_method_category_id`),
  CONSTRAINT `fk_customer_has_payment_method_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_has_payment_method_payment_method1`
    FOREIGN KEY (`payment_method_category_id`)
    REFERENCES `payment_method` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `credit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `credit_card` ;

CREATE TABLE IF NOT EXISTS `credit_card` (
  `credit_card_id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `exp_date` VARCHAR(45) NOT NULL,
  `security_code` INT NOT NULL,
  `card_number` INT NULL,
  `payment_method_payment_id` INT NOT NULL,
  PRIMARY KEY (`credit_card_id`, `payment_method_payment_id`),
  INDEX `fk_credit_card_payment_method1_idx` (`payment_method_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_credit_card_payment_method1`
    FOREIGN KEY (`payment_method_payment_id`)
    REFERENCES `payment_method` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `bank_deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_deposit` ;

CREATE TABLE IF NOT EXISTS `bank_deposit` (
  `bank_acct_id` INT NOT NULL,
  `bank_name` VARCHAR(255) NOT NULL,
  `acct_num` INT NOT NULL,
  `routing_num` INT NOT NULL,
  `payment_method_payment_id` INT NOT NULL,
  PRIMARY KEY (`bank_acct_id`, `payment_method_payment_id`),
  INDEX `fk_bank_deposit_payment_method1_idx` (`payment_method_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_bank_deposit_payment_method1`
    FOREIGN KEY (`payment_method_payment_id`)
    REFERENCES `payment_method` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- CREATE TRIGGER t_reg_insert AFTER INSERT ON general_user
	

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
