-- MySQL Script generated by MySQL Workbench
-- Mon Dec 13 18:38:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ArtGalleryManagementDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ArtGalleryManagementDB` ;

-- -----------------------------------------------------
-- Schema ArtGalleryManagementDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ArtGalleryManagementDB` DEFAULT CHARACTER SET utf8 ;
USE `ArtGalleryManagementDB` ;

-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`gallery` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `phone_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`registered_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`registered_user` (
  `id` INT NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `registered_user_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`id`, `user`),
  INDEX `fk_customer_registered_user1_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_customer_registered_user1`
    FOREIGN KEY (`user`)
    REFERENCES `ArtGalleryManagementDB`.`registered_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artwork` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` INT NULL,
  `available` TINYINT NOT NULL,
  `image` VARCHAR(255) NULL COMMENT 'could have image, path to img file.',
  `gallery` INT NOT NULL,
  `customer_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_artwork_gallery1_idx` (`gallery` ASC) VISIBLE,
  INDEX `fk_artwork_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_artwork_gallery1`
    FOREIGN KEY (`gallery`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ArtGalleryManagementDB`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artist` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `bio` VARCHAR(255) NULL,
  `birthday` DATE NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `registered_user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_artist_registered_user1_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_artist_registered_user1`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `ArtGalleryManagementDB`.`registered_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`make`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`make` (
  `artist` INT NOT NULL,
  `artwork` INT NOT NULL,
  INDEX `fk_artist_has_artwork_artwork1_idx` (`artwork` ASC) VISIBLE,
  INDEX `fk_artist_has_artwork_artist_idx` (`artist` ASC) VISIBLE,
  CONSTRAINT `fk_artist_has_artwork_artist`
    FOREIGN KEY (`artist`)
    REFERENCES `ArtGalleryManagementDB`.`artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artist_has_artwork_artwork1`
    FOREIGN KEY (`artwork`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`address` (
  `id` INT NOT NULL,
  `street_num` INT NOT NULL,
  `street_name` VARCHAR(100) NOT NULL,
  `zip` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `customer` INT NOT NULL,
  PRIMARY KEY (`id`, `customer`),
  INDEX `fk_address_copy1_customer1_idx` (`customer` ASC) VISIBLE,
  CONSTRAINT `fk_address_copy1_customer1`
    FOREIGN KEY (`customer`)
    REFERENCES `ArtGalleryManagementDB`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`director` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone_num` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`id`, `user`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone_num` ASC) VISIBLE,
  INDEX `fk_director_registered_user1_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_director_registered_user1`
    FOREIGN KEY (`user`)
    REFERENCES `ArtGalleryManagementDB`.`registered_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`runs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`runs` (
  `gallery` INT NOT NULL,
  `director` INT NOT NULL,
  INDEX `fk_gallery_has_director_director1_idx` (`director` ASC) VISIBLE,
  INDEX `fk_gallery_has_director_gallery1_idx` (`gallery` ASC) VISIBLE,
  CONSTRAINT `fk_gallery_has_director_gallery1`
    FOREIGN KEY (`gallery`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gallery_has_director_director1`
    FOREIGN KEY (`director`)
    REFERENCES `ArtGalleryManagementDB`.`director` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`payment` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `customer` INT NOT NULL,
  PRIMARY KEY (`id`, `customer`),
  INDEX `fk_payment_customer1_idx` (`customer` ASC) VISIBLE,
  CONSTRAINT `fk_payment_customer1`
    FOREIGN KEY (`customer`)
    REFERENCES `ArtGalleryManagementDB`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`card` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `number` INT NOT NULL,
  `exp_date` DATE NOT NULL,
  `security_code` INT NOT NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`id`, `payment_id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_card_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `ArtGalleryManagementDB`.`payment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`deposit` (
  `id` INT NOT NULL,
  `bank_name` VARCHAR(100) NOT NULL,
  `acct_num` INT NOT NULL,
  `routing_num` INT NOT NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`id`, `payment_id`),
  UNIQUE INDEX `number_UNIQUE` (`acct_num` ASC) VISIBLE,
  INDEX `fk_card_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_payment10`
    FOREIGN KEY (`payment_id`)
    REFERENCES `ArtGalleryManagementDB`.`payment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`address` (
  `id` INT NOT NULL,
  `street_num` INT NOT NULL,
  `street_name` VARCHAR(100) NOT NULL,
  `zip` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `customer` INT NOT NULL,
  PRIMARY KEY (`id`, `customer`),
  INDEX `fk_address_copy1_customer1_idx` (`customer` ASC) VISIBLE,
  CONSTRAINT `fk_address_copy1_customer1`
    FOREIGN KEY (`customer`)
    REFERENCES `ArtGalleryManagementDB`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`painting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`painting` (
  `id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork1`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`sculpture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`sculpture` (
  `id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork10`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`photograph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`photograph` (
  `id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork11`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`graphic_design`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`graphic_design` (
  `id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  PRIMARY KEY (`id`, `artwork_id`),
  INDEX `fk_painting_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_painting_artwork12`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`style` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`style_has_painting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`style_has_painting` (
  `style_id` INT NOT NULL,
  `painting_id` INT NOT NULL,
  PRIMARY KEY (`style_id`, `painting_id`),
  INDEX `fk_style_has_painting_painting1_idx` (`painting_id` ASC) VISIBLE,
  INDEX `fk_style_has_painting_style1_idx` (`style_id` ASC) VISIBLE,
  CONSTRAINT `fk_style_has_painting_style1`
    FOREIGN KEY (`style_id`)
    REFERENCES `ArtGalleryManagementDB`.`style` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_style_has_painting_painting1`
    FOREIGN KEY (`painting_id`)
    REFERENCES `ArtGalleryManagementDB`.`painting` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`genre` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artwork_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artwork_has_genre` (
  `artwork` INT NOT NULL,
  `genre` INT NOT NULL,
  PRIMARY KEY (`artwork`, `genre`),
  INDEX `fk_genre_has_artwork_artwork1_idx` (`artwork` ASC) VISIBLE,
  INDEX `fk_genre_has_artwork_genre1_idx` (`genre` ASC) VISIBLE,
  CONSTRAINT `fk_genre_has_artwork_genre1`
    FOREIGN KEY (`genre`)
    REFERENCES `ArtGalleryManagementDB`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_has_artwork_artwork1`
    FOREIGN KEY (`artwork`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`material` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`material_has_sculpture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`material_has_sculpture` (
  `material_id` INT NOT NULL,
  `sculpture_id` INT NOT NULL,
  PRIMARY KEY (`material_id`, `sculpture_id`),
  INDEX `fk_material_has_sculpture_sculpture1_idx` (`sculpture_id` ASC) VISIBLE,
  INDEX `fk_material_has_sculpture_material1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_material_has_sculpture_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `ArtGalleryManagementDB`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_has_sculpture_sculpture1`
    FOREIGN KEY (`sculpture_id`)
    REFERENCES `ArtGalleryManagementDB`.`sculpture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
